version: "3"

services:
  django:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: django
    command: python3 swisscapital_management/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
