# Generated by Django 3.2.6 on 2021-08-21 12:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=25, verbose_name='დეპარტამენტის სახელი')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=25, verbose_name='პიროვნული თვისებები')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=20, verbose_name='გვარი')),
                ('citizenship', models.CharField(max_length=20, verbose_name='მოქალაქეობა')),
                ('gender', models.CharField(choices=[('მ', 'კაცი'), ('ქ', 'ქალი')], max_length=1, verbose_name='სქესი')),
                ('person_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='პირადობა უნდა შეიცავდეს 11 ციფრს')], verbose_name='პირადი ნომერი')),
                ('date_of_birth', models.DateField(verbose_name='დაბადების თარიღი')),
                ('date_expiry', models.DateField(verbose_name='მოქმედების ვადა')),
                ('card_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='ბარათის ნომერი უნდა შეიცავდეს 11 სიმბოლოს')], verbose_name='ბარათის ნომერი')),
                ('image', models.ImageField(default='default.jpg', upload_to='images', verbose_name='სურათი')),
                ('place_of_birth', models.CharField(max_length=15, verbose_name='დაბადების ადგილი')),
                ('date_of_issue', models.DateField(verbose_name='გაცემის თარიღი')),
                ('issueing_authority', models.CharField(max_length=20, verbose_name='გამცემი ორგანი')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.department', verbose_name='დეპარტამენტი')),
                ('personal_quality', models.ManyToManyField(to='management_app.PersonalQuality', verbose_name='პიროვნული თვისებები')),
            ],
        ),
    ]
