# Generated by Django 3.2.6 on 2021-08-22 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-id'], 'verbose_name': 'დეპარტამენტები'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id'], 'verbose_name': 'თანამშრომლები'},
        ),
        migrations.AlterModelOptions(
            name='personalquality',
            options={'ordering': ['-id'], 'verbose_name': 'პიროვნული თვისებები'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='card_number',
            field=models.CharField(help_text='შეიყვანეთ 11 სიმბოლო', max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=9, message='ბარათის ნომერი უნდა შეიცავდეს 9 სიმბოლოს'), django.core.validators.RegexValidator(message='არასწორი ფორმატი ბარათი უნდა შეიცავდეს 2 ციფრს შემდეგ 2 დიდ ლათინურ ასოს და ბოლოს 5 ციფრს', regex='^[0-9]{2}[A-Z]{2}[0-9]{5}$')], verbose_name='ბარათის ნომერი'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='person_number',
            field=models.CharField(help_text='შეიყვანეთ მცოლოდ 11 ციფრი', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='პირადობა უნდა შეიცავდეს მხოლოდ 11 ციფრს'), django.core.validators.RegexValidator(message='პირადობა უნდა შეიცავდეს მხოლოდ 11 ციფრს', regex='^[0-9]*$')], verbose_name='პირადი ნომერი'),
        ),
    ]
